# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester_name',
            field=models.ForeignKey(db_column=b'semester_name', on_delete=django.db.models.deletion.CASCADE, to='time_table_test.Semester'),
        ),
    ]
