# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_test', '0002_auto_20171202_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_subject',
            name='sub_code',
            field=models.ForeignKey(db_column=b'sub_code', on_delete=django.db.models.deletion.CASCADE, to='time_table_test.Subject'),
        ),
        migrations.AlterField(
            model_name='subject_scheme',
            name='sub_code',
            field=models.ForeignKey(db_column=b'sub_code', on_delete=django.db.models.deletion.CASCADE, to='time_table_test.Subject'),
        ),
    ]
