# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_test', '0003_auto_20171202_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_day_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.IntegerField()),
                ('semester_name', models.ForeignKey(db_column=b'semester_name', on_delete=django.db.models.deletion.CASCADE, to='time_table_test.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_timeslot_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_timeslot', models.IntegerField()),
                ('semester_name', models.ForeignKey(db_column=b'semester_name', on_delete=django.db.models.deletion.CASCADE, to='time_table_test.Semester')),
            ],
        ),
    ]
